Feature: Create New Session.

  Scenario Outline: Try to create new session with invalid details, then it will throw error.
    Given Session details user_id: "<user_id>", jwt_token: "<jwt_token>", session_id: "<session_id>",user_agent: "<user_agent>",device: "<device>",ip_address: "<ip_address>",city: "<city>",state: "<state>" and country: "<country>" to create new session
    When Try to create new session
    Then It will throw error: "<error>" with message: "<message>" while creating new session
    # And GetSessionsDetailByEmail function will call <getSessionsDetailByEmailFunctionCallCount> time while creating new session
    # And getSessionsDetailByMobile function will call <getSessionsDetailByMobileFunctionCallCount> time while creating new session
    # And encryptPassword function will call <encryptPasswordFunctionCallCount> time while creating new session
    # And createSession function will call <createSessionFunctionCallCount> time while creating new session

    Examples:
      | user_id                                  | jwt_token         | session_id                          | user_agent    |  device       | ip_address          | city      | state      | country       | getSessionsDetailByEmailFunctionCallCount | getSessionsDetailByMobileFunctionCallCount | encryptPasswordFunctionCallCount | createSessionFunctionCallCount | error           | message                                                |
      |                                          |                   |                                     |               |               |                     |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"user_id\" is required"                                   |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     |                   |                                     |               |               |                     |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"jwt_token\" is required"                                  |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  |                                     |               |               |                     |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"session_id\" is required"                        |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398|               |               |                     |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"user_agent\" is required"                                 |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   |               |                     |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"device\" is required"                              |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   | desktop       |                     |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"ip_address\" is required" |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   | desktop       | 103.217.84.112      |           |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"city\" is required" |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   | desktop       | 103.217.84.112      | Jalalpur  |            |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"state\" is required" |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   | desktop       | 103.217.84.112      | Jalalpur  | GJ         |               |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"country\" is required" |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb0        | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   | desktop       | 103.217.84.112      | Jalalpur  | GJ         | IN            |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"user_id\" must be a valid GUID" |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1 | fa15c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0      | desktop       | 103.217.84.112      | Jalalpur  | GJ         | IN            |  0                                      | 0                                       | 0                                | 0                           | ValidationError | "\"session_id\" must be a valid GUID" |
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1 | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0    | desktop       | 1037.84.112      | Jalalpur  | GJ         | IN            |  0                                      | 0                                       | 0                                | 0                              | ValidationError | "\"ip_address\" must be a valid ip address with a optional CIDR" |
      | d8cfe36a-81f5-4d96-8a54-4ac923012c       | eyJhbGciOiJIUzI1 | fa15c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0      | desktop       | 103.217.84.112      | Jalalpur  | GJ         | IN            |  0                                      | 0                                       | 0                                | 0                             | ValidationError | "\"user_id\" must be a valid GUID" |
  Scenario Outline: Try to create new session with valid inputs, then it will create new session.
    Given Session details user_id: "<user_id>", jwt_token: "<jwt_token>", session_id: "<session_id>",user_agent: "<user_agent>",device: "<device>",ip_address: "<ip_address>",city: "<city>",state: "<state>" and country: "<country>" to create new session
    When Try to create new session
    Then It will create new session with details: "<newSessionDetails>"
    # And GetSessionsDetailByEmail function will call <getSessionsDetailByEmailFunctionCallCount> time while creating new session
    # And getSessionsDetailByMobile function will call <getSessionsDetailByMobileFunctionCallCount> time while creating new session
    # And encryptPassword function will call <encryptPasswordFunctionCallCount> time while creating new session
    # And createSession function will call <createSessionFunctionCallCount> time while creating new session

    # Examples:
    #   | name       | email                   | mobile        | password   | newSessionDetails | encryptedPassword             | getSessionsDetailByEmailFunctionCallCount | getSessionsDetailByMobileFunctionCallCount | encryptPasswordFunctionCallCount | createSessionFunctionCallCount |
    #   | Aman Gupta | aman.gupta@rapidops.com | +917024166349 | 1234567890 | '{"id": 1}'    | fue8374834ry8y832479#$#@iou43 | 1                                      | 1                                       | 1                                | 1                           |
 Examples:
      | user_id                                  | jwt_token         | session_id                          | user_agent    |  device       | ip_address          | city      | state      | country       | getSessionsDetailByEmailFunctionCallCount | getSessionsDetailByMobileFunctionCallCount | encryptPasswordFunctionCallCount | createSessionFunctionCallCount | newSessionDetails |                                                 
    
      | d8cfe36a-81f5-4d96-8a54-4ac923cb012c     | eyJhbGciOiJIUzI1  | fa1507c0-05f6-11ee-aacd-d5f50a890398| Mozilla/5.0   | desktop       | 103.217.84.112      | Jalalpur  | GJ         | IN            |  0                                      | 0                                       | 0                                | 0                             | '{"id": 1}'  | 
